
spring:
  application:
    name: tulingmall-authcenter
tuling:
    jwt:
      keyPairName: jwt.jks
      keyPairAlias: jwt
      keyPairSecret: 123456
      keyPairStoreSecret: 123456
server:
  port: 9998